---
- name: install apt packages
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: latest
  with_items:
    - python3-psycopg2
    - libpq-dev
    - postgresql
    - python3-pip

- name: update pip3
  pip:
    name: pip
    extra_args: --upgrade

- name: install pip packages
  pip:
    name: "{{ item }}"
    state: latest
  with_items:
    - django
    - gunicorn
    - django-cors-headers
    - djangorestframework
