---
# Add apt key and repo for nginx
- apt_key:
    url: http://nginx.org/keys/nginx_signing.key
    state: present

- apt_repository:
    repo: 'deb http://nginx.org/packages/mainline/ubuntu/ xenial nginx'
    state: present
    filename: 'nginx'

- name: install apt packages
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: latest
  with_items:
    - chromium-browser
    - python3-psycopg2
    - libpq-dev
    - postgresql
    - python3-pip
    - nginx

- name: update pip3
  pip:
    name: pip
    extra_args: --upgrade

- name: install django
  pip:
    name: django
    version: 2.1

- name: install gunicorn
  pip:
    name: gunicorn
    version: 19.9.0

- name: install django-cors-headers
  pip:
    name: django-cors-headers
    version: 2.4.0

- name: install djangorestframework
  pip:
    name: djangorestframework
    version: 3.8.2

- name: install django-filter
  pip:
    name: django-filter
    version: 2.0.0

- name: install djangorestframework-queryfields
  pip:
    name: djangorestframework-queryfields
    version: 1.0.0
