---
# Add apt key and repo for nginx
- apt_key:
    url: http://nginx.org/keys/nginx_signing.key
    state: present

- apt_repository:
    repo: 'deb http://nginx.org/packages/mainline/ubuntu/ xenial nginx'
    state: present
    filename: 'nginx'

- name: install apt packages
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: latest
  with_items:
    - chromium-browser
    - python3-psycopg2
    - libpq-dev
    - postgresql
    - python3-pip
    - nginx

- name: update pip3
  pip:
    name: pip
    extra_args: --upgrade

- name: install pip packages
  pip:
    name: "{{ item }}"
    state: latest
  with_items:
    - django
    - gunicorn
    - django-cors-headers
    - djangorestframework
    - django-filter
